/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#ffb19b",
        "surface-container-high": "#1d2024",
        "surface-container-highest": "#23262a",
        "tertiary-fixed": "#f39cfb",
        "error": "#ff716c",
        "tertiary": "#fab0ff",
        "inverse-primary": "#006976",
        "surface-container": "#171a1d",
        "primary-fixed": "#00e3fd",
        "inverse-on-surface": "#535559",
        "error-container": "#9f0519",
        "surface-dim": "#0c0e11",
        "secondary-dim": "#ff734a",
        "tertiary-container": "#f39cfb",
        "on-surface": "#f9f9fd",
        "on-primary-fixed": "#003840",
        "inverse-surface": "#f9f9fd",
        "surface-variant": "#23262a",
        "on-tertiary": "#6a1f77",
        "on-error": "#490006",
        "on-surface-variant": "#aaabaf",
        "surface-container-low": "#111417",
        "error-dim": "#d7383b",
        "outline": "#747579",
        "primary-container": "#00e3fd",
        "on-error-container": "#ffa8a3",
        "on-primary": "#005762",
        "on-secondary-fixed": "#661700",
        "on-secondary-container": "#fff6f4",
        "outline-variant": "#46484b",
        "primary-dim": "#00d4ec",
        "surface": "#0c0e11",
        "tertiary-fixed-dim": "#e48fed",
        "on-primary-container": "#004d57",
        "secondary": "#ff734a",
        "primary": "#81ecff",
        "on-background": "#f9f9fd",
        "on-secondary-fixed-variant": "#982700",
        "surface-container-lowest": "#000000",
        "on-tertiary-fixed-variant": "#6a1f77",
        "secondary-container": "#b02f00",
        "background": "#0c0e11",
        "surface-bright": "#292c31",
        "primary-fixed-dim": "#00d4ec",
        "on-tertiary-fixed": "#41004d",
        "surface-tint": "#81ecff",
        "tertiary-dim": "#e48fed",
        "secondary-fixed": "#ffc4b4",
        "on-tertiary-container": "#60136d",
        "on-primary-fixed-variant": "#005762",
        "on-secondary": "#430c00"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
